// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZhmLQDp3r50_eNDp82VycaRaLf6xF6Do',
    appId: '1:550354354647:web:b178796906752f29d9cb92',
    messagingSenderId: '550354354647',
    projectId: 'miagrd',
    authDomain: 'miagrd.firebaseapp.com',
    storageBucket: 'miagrd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnJ3YrJWlnuLGIDmRYk6TiwApNXZuAOGw',
    appId: '1:550354354647:android:88ccb979cc0b29bcd9cb92',
    messagingSenderId: '550354354647',
    projectId: 'miagrd',
    storageBucket: 'miagrd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT09hUo63gos3lW2iRoTeptjZnTCwp8Yg',
    appId: '1:550354354647:ios:3553661b8fa7d812d9cb92',
    messagingSenderId: '550354354647',
    projectId: 'miagrd',
    storageBucket: 'miagrd.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT09hUo63gos3lW2iRoTeptjZnTCwp8Yg',
    appId: '1:550354354647:ios:45ff5cf041cca931d9cb92',
    messagingSenderId: '550354354647',
    projectId: 'miagrd',
    storageBucket: 'miagrd.appspot.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
